##################################################
# Generated by phansible.com
##################################################

#If your Vagrant version is lower than 1.5, you can still use this provisioning
#by commenting or removing the line below and providing the config.vm.box_url parameter,
#if it's not already defined in this Vagrantfile. Keep in mind that you won't be able
#to use the Vagrant Cloud and other newer Vagrant features.
Vagrant.require_version ">= 1.5"

# Check to determine whether we're on a windows or linux/os-x host,
# later on we use this to launch ansible in the supported way
# source: https://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby
def which(cmd)
    exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
    ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
        exts.each { |ext|
            exe = File.join(path, "#{cmd}#{ext}")
            return exe if File.executable? exe
        }
    end
    return nil
end

require 'yaml'
other_configs = YAML.load_file('ansible/vars/common.yml')

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
    v.name = "local_dev_environment"
        v.customize [
            "modifyvm", :id,
            "--name", "local_dev_environment",
            "--memory", 512,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box = "dev/centos65-x64-ansible"
    config.vm.box_url = "http://104.236.100.209/centos65-x64-ansible.box"
    config.vm.network :private_network, ip: "192.168.56.99"
    config.ssh.forward_agent = true

    #############################################################
    # Ansible provisioning (you need to have ansible installed)
    #############################################################

    
    if which('ansible-playbook')
        config.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/playbook.yml"
            ansible.inventory_path = "ansible/inventories"
            ansible.limit = 'all'
            ansible.extra_vars = {
                private_interface: "192.168.56.99",
                hostname: "local_dev_environment"
            }
			ansible.sudo = true
			ansible.verbose = 'vvvv'
        end
    else
        config.vm.provision :shell, path: "ansible/windows.sh", args: ["local_dev_environment"]
    end

    
    config.vm.synced_folder "./", "/vagrant", type: "nfs"
    config.vm.synced_folder "./irmec-website", "/var/www/html/irmec-website", type: "nfs"	
	# Uncomment the line below if you don't want to use Samba for file sharing and use default virtualbox share (or NFS if supported by your OS). Make sure the value of host_doc_root on common.yml is updated to the correct path on host machine.
	#config.vm.synced_folder other_configs['host_doc_root'], "/var/www/html", type: "nfs"

    #Port forwarding for HTTP
    config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true

    # Port forwarding for SSH (disabled by default - use vagrant reload)
    config.vm.network "forwarded_port", guest: 22, host: 22000, auto_correct: true

    # Port forwarding for MySQL (disabled by default - use vagrant reload)
    config.vm.network "forwarded_port", guest: 3306, host: 33000, auto_correct: true

end
