---
    #MySQL settings
    mysql_packages:
      - mysql56u
      - mysql56u-server
      - MySQL-python
    mysql_root_password: super-secure-password
    mysql_enabled_on_startup: yes
    mysql_enablerepo: "ius-archive"
    mysql_databases:
      - name: example_db
        encoding: utf8
        collation: utf8_general_ci
    mysql_users:
      - name: root_user
        host: "%"
        password: vagrantmysql
        priv: "*.*:ALL"
    mysql_innodb_buffer_pool_size: 128M
    mysql_key_buffer_size: 128M
    mysql_thread_cache_size: 128
    mysql_key_buffer_size: 128M
    mysql_innodb_buffer_pool_size: 128M
    mysql_table_open_cache: 128
    mysql_max_connections: 100